version: '3.9'

services:
  cache:
    image: redis:7.4.2-alpine
    container_name: redis_cache
    ports:
      - '6379:6379'
    networks:
      - my-network
  queue:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq_queue
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - my-network
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: online-shop
    container_name: postgres_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      - cache

    networks:
      - my-network
networks:
  my-network:
    driver: bridge
  