name: cd_deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub (optional)
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull hieutran03/online-shop:latest

    - name: Start Docker Compose
      run: |
        cd $GITHUB_WORKSPACE  # Navigate to the repository directory
        docker compose up -d  # Use 'docker compose' (V2) instead of 'docker-compose'