name: cd_deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull hieutran03/online-shop:latest

    - name: Start Docker Compose
      run: |
        cd $GITHUB_WORKSPACE  # Navigate to the repository directory
        docker-compose up -d